// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0xCDCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backgroundImage = lv_image_create(ui_MainScreen);
    lv_image_set_src(ui_backgroundImage, &ui_img_background_resized_png);
    lv_obj_set_width(ui_backgroundImage, 320);
    lv_obj_set_height(ui_backgroundImage, 240);
    lv_obj_set_x(ui_backgroundImage, 1);
    lv_obj_set_y(ui_backgroundImage, -1);
    lv_obj_set_align(ui_backgroundImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backgroundImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_backgroundImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_backgroundImage, 260);

    ui_statusBar = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_statusBar, 330);
    lv_obj_set_height(ui_statusBar, 32);
    lv_obj_set_x(ui_statusBar, -2);
    lv_obj_set_y(ui_statusBar, -106);
    lv_obj_set_align(ui_statusBar, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_statusBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_statusBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_statusBar, lv_color_hex(0x6B6B6B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_statusBar, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_statusBar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_statusBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batteryIcon = lv_image_create(ui_statusBar);
    lv_image_set_src(ui_batteryIcon, &ui_img_battery_full_transparent_png);
    lv_obj_set_width(ui_batteryIcon, 32);
    lv_obj_set_height(ui_batteryIcon, 32);
    lv_obj_set_x(ui_batteryIcon, 100);
    lv_obj_set_y(ui_batteryIcon, 0);
    lv_obj_set_align(ui_batteryIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_batteryIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_batteryIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_batteryIcon, 100);

    ui_sdIcon = lv_image_create(ui_statusBar);
    lv_image_set_src(ui_sdIcon, &ui_img_sd_png);
    lv_obj_set_width(ui_sdIcon, 32);
    lv_obj_set_height(ui_sdIcon, 32);
    lv_obj_set_x(ui_sdIcon, -100);
    lv_obj_set_y(ui_sdIcon, -1);
    lv_obj_set_align(ui_sdIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sdIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_sdIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_sdIcon, 28);

    ui_time = lv_label_create(ui_statusBar);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, 47);
    lv_obj_set_y(ui_time, 0);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "05:12:00");
    lv_obj_set_style_text_color(ui_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imageButton1Container = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_imageButton1Container);
    lv_obj_set_width(ui_imageButton1Container, 98);
    lv_obj_set_height(ui_imageButton1Container, 106);
    lv_obj_set_x(ui_imageButton1Container, -85);
    lv_obj_set_y(ui_imageButton1Container, -40);
    lv_obj_set_align(ui_imageButton1Container, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_imageButton1Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imageButton1 = lv_button_create(ui_imageButton1Container);
    lv_obj_set_width(ui_imageButton1, 75);
    lv_obj_set_height(ui_imageButton1, 75);
    lv_obj_set_x(ui_imageButton1, -1);
    lv_obj_set_y(ui_imageButton1, 1);
    lv_obj_set_align(ui_imageButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imageButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_imageButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_imageButton1, lv_color_hex(0x6B6B6B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_imageButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_imageButton1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_imageButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_imageButton1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_imageButton1, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_imageButton1, 5, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_imageButton1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_imageButton1Icon = lv_image_create(ui_imageButton1Container);
    lv_image_set_src(ui_imageButton1Icon, &ui_img_mail_transparent_resized_png);
    lv_obj_set_width(ui_imageButton1Icon, 48);
    lv_obj_set_height(ui_imageButton1Icon, 48);
    lv_obj_set_x(ui_imageButton1Icon, -1);
    lv_obj_set_y(ui_imageButton1Icon, -4);
    lv_obj_set_align(ui_imageButton1Icon, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_imageButton1Icon, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imageButton1Label = lv_label_create(ui_imageButton1Container);
    lv_obj_set_width(ui_imageButton1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imageButton1Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imageButton1Label, -1);
    lv_obj_set_y(ui_imageButton1Label, 28);
    lv_obj_set_align(ui_imageButton1Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_imageButton1Label, "Message");

    ui_imageButton2Container = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_imageButton2Container);
    lv_obj_set_width(ui_imageButton2Container, 98);
    lv_obj_set_height(ui_imageButton2Container, 106);
    lv_obj_set_x(ui_imageButton2Container, 0);
    lv_obj_set_y(ui_imageButton2Container, -40);
    lv_obj_set_align(ui_imageButton2Container, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_imageButton2Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imageButton2 = lv_button_create(ui_imageButton2Container);
    lv_obj_set_width(ui_imageButton2, 75);
    lv_obj_set_height(ui_imageButton2, 75);
    lv_obj_set_x(ui_imageButton2, -1);
    lv_obj_set_y(ui_imageButton2, 1);
    lv_obj_set_align(ui_imageButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imageButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_imageButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_imageButton2, lv_color_hex(0x6B6B6B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_imageButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_imageButton2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_imageButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_imageButton2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_imageButton2, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_imageButton2, 5, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_imageButton2, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_imageButton2Icon = lv_image_create(ui_imageButton2Container);
    lv_image_set_src(ui_imageButton2Icon, &ui_img_satellite_transparent_resized_outlined_png);
    lv_obj_set_width(ui_imageButton2Icon, 48);
    lv_obj_set_height(ui_imageButton2Icon, 48);
    lv_obj_set_x(ui_imageButton2Icon, -1);
    lv_obj_set_y(ui_imageButton2Icon, -4);
    lv_obj_set_align(ui_imageButton2Icon, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_imageButton2Icon, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_imageButton2Icon, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_imageButton2Icon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_imageButton2Icon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_imageButton2Icon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_imageButton2Icon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_imageButton2Icon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imageButton2Label = lv_label_create(ui_imageButton2Container);
    lv_obj_set_width(ui_imageButton2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imageButton2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imageButton2Label, -1);
    lv_obj_set_y(ui_imageButton2Label, 28);
    lv_obj_set_align(ui_imageButton2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_imageButton2Label, "Sats");

    ui_imageButton3Container = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_imageButton3Container);
    lv_obj_set_width(ui_imageButton3Container, 98);
    lv_obj_set_height(ui_imageButton3Container, 106);
    lv_obj_set_x(ui_imageButton3Container, 85);
    lv_obj_set_y(ui_imageButton3Container, -40);
    lv_obj_set_align(ui_imageButton3Container, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_imageButton3Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imageButton3 = lv_button_create(ui_imageButton3Container);
    lv_obj_set_width(ui_imageButton3, 75);
    lv_obj_set_height(ui_imageButton3, 75);
    lv_obj_set_x(ui_imageButton3, -1);
    lv_obj_set_y(ui_imageButton3, 1);
    lv_obj_set_align(ui_imageButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imageButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_imageButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_imageButton3, lv_color_hex(0x6B6B6B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_imageButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_imageButton3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_imageButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_imageButton3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_imageButton3, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_imageButton3, 5, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_imageButton3, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_imageButton3Icon = lv_image_create(ui_imageButton3Container);
    lv_image_set_src(ui_imageButton3Icon, &ui_img_settings_transparent_resized_outlined_png);
    lv_obj_set_width(ui_imageButton3Icon, 48);
    lv_obj_set_height(ui_imageButton3Icon, 48);
    lv_obj_set_x(ui_imageButton3Icon, -1);
    lv_obj_set_y(ui_imageButton3Icon, -4);
    lv_obj_set_align(ui_imageButton3Icon, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_imageButton3Icon, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imageButton3Label = lv_label_create(ui_imageButton3Container);
    lv_obj_set_width(ui_imageButton3Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imageButton3Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imageButton3Label, -1);
    lv_obj_set_y(ui_imageButton3Label, 28);
    lv_obj_set_align(ui_imageButton3Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_imageButton3Label, "Settings");

    ui_imageButton4Container = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_imageButton4Container);
    lv_obj_set_width(ui_imageButton4Container, 98);
    lv_obj_set_height(ui_imageButton4Container, 106);
    lv_obj_set_x(ui_imageButton4Container, -85);
    lv_obj_set_y(ui_imageButton4Container, 45);
    lv_obj_set_align(ui_imageButton4Container, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_imageButton4Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imageButton4 = lv_button_create(ui_imageButton4Container);
    lv_obj_set_width(ui_imageButton4, 75);
    lv_obj_set_height(ui_imageButton4, 75);
    lv_obj_set_x(ui_imageButton4, -1);
    lv_obj_set_y(ui_imageButton4, 1);
    lv_obj_set_align(ui_imageButton4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imageButton4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_imageButton4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_imageButton4, lv_color_hex(0x6B6B6B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_imageButton4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_imageButton4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_imageButton4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_imageButton4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_imageButton4, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_imageButton4, 5, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_imageButton4, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_imageButton4Icon = lv_image_create(ui_imageButton4Container);
    lv_image_set_src(ui_imageButton4Icon, &ui_img_folder_transparent_resized_outlined_png);
    lv_obj_set_width(ui_imageButton4Icon, 48);
    lv_obj_set_height(ui_imageButton4Icon, 48);
    lv_obj_set_x(ui_imageButton4Icon, -1);
    lv_obj_set_y(ui_imageButton4Icon, -4);
    lv_obj_set_align(ui_imageButton4Icon, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_imageButton4Icon, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imageButton4Label = lv_label_create(ui_imageButton4Container);
    lv_obj_set_width(ui_imageButton4Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imageButton4Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imageButton4Label, -1);
    lv_obj_set_y(ui_imageButton4Label, 28);
    lv_obj_set_align(ui_imageButton4Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_imageButton4Label, "Folder");

    ui_imageButton5Container = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_imageButton5Container);
    lv_obj_set_width(ui_imageButton5Container, 98);
    lv_obj_set_height(ui_imageButton5Container, 106);
    lv_obj_set_x(ui_imageButton5Container, 0);
    lv_obj_set_y(ui_imageButton5Container, 45);
    lv_obj_set_align(ui_imageButton5Container, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_imageButton5Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imageButton5 = lv_button_create(ui_imageButton5Container);
    lv_obj_set_width(ui_imageButton5, 75);
    lv_obj_set_height(ui_imageButton5, 75);
    lv_obj_set_x(ui_imageButton5, -1);
    lv_obj_set_y(ui_imageButton5, 1);
    lv_obj_set_align(ui_imageButton5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imageButton5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_imageButton5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_imageButton5, lv_color_hex(0x6B6B6B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_imageButton5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_imageButton5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_imageButton5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_imageButton5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_imageButton5, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_imageButton5, 5, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_imageButton5, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_imageButton5Icon = lv_image_create(ui_imageButton5Container);
    lv_image_set_src(ui_imageButton5Icon, &ui_img_folder_transparent_resized_outlined_png);
    lv_obj_set_width(ui_imageButton5Icon, 48);
    lv_obj_set_height(ui_imageButton5Icon, 48);
    lv_obj_set_x(ui_imageButton5Icon, -1);
    lv_obj_set_y(ui_imageButton5Icon, -4);
    lv_obj_set_align(ui_imageButton5Icon, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_imageButton5Icon, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imageButton5Label = lv_label_create(ui_imageButton5Container);
    lv_obj_set_width(ui_imageButton5Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imageButton5Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imageButton5Label, -1);
    lv_obj_set_y(ui_imageButton5Label, 28);
    lv_obj_set_align(ui_imageButton5Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_imageButton5Label, "tbd");

    ui_imageButton6Container = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_imageButton6Container);
    lv_obj_set_width(ui_imageButton6Container, 98);
    lv_obj_set_height(ui_imageButton6Container, 106);
    lv_obj_set_x(ui_imageButton6Container, 85);
    lv_obj_set_y(ui_imageButton6Container, 45);
    lv_obj_set_align(ui_imageButton6Container, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_imageButton6Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imageButton6 = lv_button_create(ui_imageButton6Container);
    lv_obj_set_width(ui_imageButton6, 75);
    lv_obj_set_height(ui_imageButton6, 75);
    lv_obj_set_x(ui_imageButton6, -1);
    lv_obj_set_y(ui_imageButton6, 1);
    lv_obj_set_align(ui_imageButton6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imageButton6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_imageButton6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_imageButton6, lv_color_hex(0x6B6B6B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_imageButton6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_imageButton6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_imageButton6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_imageButton6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_opa(ui_imageButton6, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_imageButton6, 5, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_imageButton6, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_imageButton6Icon = lv_image_create(ui_imageButton6Container);
    lv_image_set_src(ui_imageButton6Icon, &ui_img_folder_transparent_resized_outlined_png);
    lv_obj_set_width(ui_imageButton6Icon, 48);
    lv_obj_set_height(ui_imageButton6Icon, 48);
    lv_obj_set_x(ui_imageButton6Icon, -1);
    lv_obj_set_y(ui_imageButton6Icon, -4);
    lv_obj_set_align(ui_imageButton6Icon, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_imageButton6Icon, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imageButton6Label = lv_label_create(ui_imageButton6Container);
    lv_obj_set_width(ui_imageButton6Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imageButton6Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imageButton6Label, -1);
    lv_obj_set_y(ui_imageButton6Label, 28);
    lv_obj_set_align(ui_imageButton6Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_imageButton6Label, "tbd");

    ui_textButton1Container = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_textButton1Container, 86);
    lv_obj_set_height(ui_textButton1Container, 34);
    lv_obj_set_x(ui_textButton1Container, -87);
    lv_obj_set_y(ui_textButton1Container, 103);
    lv_obj_set_align(ui_textButton1Container, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_textButton1Container, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_textButton1Container, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_textButton1Container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_textButton1Container, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_textButton1Container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textButton1 = lv_button_create(ui_textButton1Container);
    lv_obj_set_width(ui_textButton1, 80);
    lv_obj_set_height(ui_textButton1, 30);
    lv_obj_set_x(ui_textButton1, 1);
    lv_obj_set_y(ui_textButton1, 0);
    lv_obj_set_align(ui_textButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_textButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_textButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_textButton1, lv_color_hex(0x6A696A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_textButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_textButton1, lv_color_hex(0x942094), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_textButton1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_textButton1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_textButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_textButton1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_textButton1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_textButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_textButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_textButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textButton1Label = lv_label_create(ui_textButton1Container);
    lv_obj_set_width(ui_textButton1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textButton1Label, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_textButton1Label, -3);
    lv_obj_set_y(ui_textButton1Label, 1);
    lv_obj_set_align(ui_textButton1Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textButton1Label, "btn1");
    lv_obj_remove_flag(ui_textButton1Label, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_color(ui_textButton1Label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_textButton1Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_textButton1Label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_textButton1Label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_textButton1Label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_textButton1Label, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_textButton1Label, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textButton2Container = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_textButton2Container, 86);
    lv_obj_set_height(ui_textButton2Container, 34);
    lv_obj_set_x(ui_textButton2Container, -2);
    lv_obj_set_y(ui_textButton2Container, 103);
    lv_obj_set_align(ui_textButton2Container, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_textButton2Container, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_textButton2Container, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_textButton2Container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_textButton2Container, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_textButton2Container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textButton2 = lv_button_create(ui_textButton2Container);
    lv_obj_set_width(ui_textButton2, 80);
    lv_obj_set_height(ui_textButton2, 30);
    lv_obj_set_x(ui_textButton2, 1);
    lv_obj_set_y(ui_textButton2, 0);
    lv_obj_set_align(ui_textButton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_textButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_textButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_textButton2, lv_color_hex(0x6A696A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_textButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_textButton2, lv_color_hex(0x942094), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_textButton2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_textButton2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_textButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_textButton2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_textButton2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_textButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_textButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_textButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textButton2Label = lv_label_create(ui_textButton2Container);
    lv_obj_set_width(ui_textButton2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textButton2Label, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_textButton2Label, -3);
    lv_obj_set_y(ui_textButton2Label, 1);
    lv_obj_set_align(ui_textButton2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textButton2Label, "btn2");
    lv_obj_remove_flag(ui_textButton2Label, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_color(ui_textButton2Label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_textButton2Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_textButton2Label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_textButton2Label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_textButton2Label, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_textButton2Label, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_textButton2Label, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textButton3Container = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_textButton3Container, 86);
    lv_obj_set_height(ui_textButton3Container, 34);
    lv_obj_set_x(ui_textButton3Container, 83);
    lv_obj_set_y(ui_textButton3Container, 103);
    lv_obj_set_align(ui_textButton3Container, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_textButton3Container, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_textButton3Container, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_textButton3Container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_textButton3Container, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_textButton3Container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textButton3 = lv_button_create(ui_textButton3Container);
    lv_obj_set_width(ui_textButton3, 80);
    lv_obj_set_height(ui_textButton3, 30);
    lv_obj_set_x(ui_textButton3, 1);
    lv_obj_set_y(ui_textButton3, 0);
    lv_obj_set_align(ui_textButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_textButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_textButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_textButton3, lv_color_hex(0x6A696A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_textButton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_textButton3, lv_color_hex(0x942094), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_textButton3, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_textButton3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_textButton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_textButton3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_textButton3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_textButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_textButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_textButton3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textButton3Label = lv_label_create(ui_textButton3Container);
    lv_obj_set_width(ui_textButton3Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textButton3Label, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_textButton3Label, -3);
    lv_obj_set_y(ui_textButton3Label, 1);
    lv_obj_set_align(ui_textButton3Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textButton3Label, "btn3");
    lv_obj_remove_flag(ui_textButton3Label, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_color(ui_textButton3Label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_textButton3Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_textButton3Label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_textButton3Label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_textButton3Label, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_textButton3Label, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_textButton3Label, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textPopup = lv_textarea_create(ui_MainScreen);
    lv_obj_set_width(ui_textPopup, 253);
    lv_obj_set_height(ui_textPopup, 175);
    lv_obj_set_x(ui_textPopup, 0);
    lv_obj_set_y(ui_textPopup, 1);
    lv_obj_set_align(ui_textPopup, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_textPopup, "ID: 2 Seq: 4 Message 1\nID: 2 Seq: 5 Message 2\nID: 2 Seq: 6 Message 3");
    lv_textarea_set_placeholder_text(ui_textPopup, "Placeholder...");
    lv_obj_add_flag(ui_textPopup, LV_OBJ_FLAG_HIDDEN);     /// Flags



    uic_Button1 = ui_imageButton1;
    uic_Button1 = ui_imageButton2;
    uic_Button1 = ui_imageButton3;
    uic_Button1 = ui_imageButton4;
    uic_Button1 = ui_imageButton5;
    uic_Button1 = ui_imageButton6;

}
