// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void downanim_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t * ui_MainScreen;
lv_obj_t * ui_backgroundImage;
lv_obj_t * ui_statusBar;
lv_obj_t * ui_batteryIcon;
lv_obj_t * ui_sdIcon;
lv_obj_t * ui_time;
lv_obj_t * ui_imageButton1Container;
lv_obj_t * ui_imageButton1;
lv_obj_t * ui_imageButton1Icon;
lv_obj_t * ui_imageButton1Label;
lv_obj_t * ui_imageButton2Container;
lv_obj_t * ui_imageButton2;
lv_obj_t * ui_imageButton2Icon;
lv_obj_t * ui_imageButton2Label;
lv_obj_t * ui_imageButton3Container;
lv_obj_t * ui_imageButton3;
lv_obj_t * ui_imageButton3Icon;
lv_obj_t * ui_imageButton3Label;
lv_obj_t * ui_imageButton4Container;
lv_obj_t * ui_imageButton4;
lv_obj_t * ui_imageButton4Icon;
lv_obj_t * ui_imageButton4Label;
lv_obj_t * ui_imageButton5Container;
lv_obj_t * ui_imageButton5;
lv_obj_t * ui_imageButton5Icon;
lv_obj_t * ui_imageButton5Label;
lv_obj_t * ui_imageButton6Container;
lv_obj_t * ui_imageButton6;
lv_obj_t * ui_imageButton6Icon;
lv_obj_t * ui_imageButton6Label;
lv_obj_t * ui_textButton1Container;
lv_obj_t * ui_textButton1;
lv_obj_t * ui_textButton1Label;
lv_obj_t * ui_textButton2Container;
lv_obj_t * ui_textButton2;
lv_obj_t * ui_textButton2Label;
lv_obj_t * ui_textButton3Container;
lv_obj_t * ui_textButton3;
lv_obj_t * ui_textButton3Label;
lv_obj_t * ui_textPopup;
// CUSTOM VARIABLES
lv_obj_t * uic_Button1;
lv_obj_t * uic_Button1;
lv_obj_t * uic_Button1;
lv_obj_t * uic_Button1;
lv_obj_t * uic_Button1;
lv_obj_t * uic_Button1;

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void downanim_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 200);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, -50, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_y);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 1000);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_1, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_1, &_ui_anim_callback_get_opacity);
    lv_anim_start(&PropertyAnimation_1);

}

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_MainScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_MainScreen);
}
