// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void downanim_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_backgroundImage;
extern lv_obj_t * ui_statusBar;
extern lv_obj_t * ui_batteryIcon;
extern lv_obj_t * ui_sdIcon;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_imageButton1Container;
extern lv_obj_t * ui_imageButton1;
extern lv_obj_t * ui_imageButton1Icon;
extern lv_obj_t * ui_imageButton1Label;
extern lv_obj_t * ui_imageButton2Container;
extern lv_obj_t * ui_imageButton2;
extern lv_obj_t * ui_imageButton2Icon;
extern lv_obj_t * ui_imageButton2Label;
extern lv_obj_t * ui_imageButton3Container;
extern lv_obj_t * ui_imageButton3;
extern lv_obj_t * ui_imageButton3Icon;
extern lv_obj_t * ui_imageButton3Label;
extern lv_obj_t * ui_imageButton4Container;
extern lv_obj_t * ui_imageButton4;
extern lv_obj_t * ui_imageButton4Icon;
extern lv_obj_t * ui_imageButton4Label;
extern lv_obj_t * ui_imageButton5Container;
extern lv_obj_t * ui_imageButton5;
extern lv_obj_t * ui_imageButton5Icon;
extern lv_obj_t * ui_imageButton5Label;
extern lv_obj_t * ui_imageButton6Container;
extern lv_obj_t * ui_imageButton6;
extern lv_obj_t * ui_imageButton6Icon;
extern lv_obj_t * ui_imageButton6Label;
extern lv_obj_t * ui_textButton1Container;
extern lv_obj_t * ui_textButton1;
extern lv_obj_t * ui_textButton1Label;
extern lv_obj_t * ui_textButton2Container;
extern lv_obj_t * ui_textButton2;
extern lv_obj_t * ui_textButton2Label;
extern lv_obj_t * ui_textButton3Container;
extern lv_obj_t * ui_textButton3;
extern lv_obj_t * ui_textButton3Label;
extern lv_obj_t * ui_textPopup;
extern lv_obj_t * ui_entryPanel;
extern lv_obj_t * ui_textEntry;
extern lv_obj_t * ui_keyboard;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Button1;
extern lv_obj_t * uic_Button1;
extern lv_obj_t * uic_Button1;
extern lv_obj_t * uic_Button1;
extern lv_obj_t * uic_Button1;
extern lv_obj_t * uic_Button1;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_background_resized_png);    // assets/background_resized.png
LV_IMG_DECLARE(ui_img_battery_full_transparent_png);    // assets/battery_full_transparent.png
LV_IMG_DECLARE(ui_img_sd_png);    // assets/sd.png
LV_IMG_DECLARE(ui_img_mail_transparent_resized_png);    // assets/mail_transparent_resized.png
LV_IMG_DECLARE(
    ui_img_satellite_transparent_resized_outlined_png);    // assets/satellite_transparent_resized_outlined.png
LV_IMG_DECLARE(ui_img_settings_transparent_resized_outlined_png);    // assets/settings_transparent_resized_outlined.png
LV_IMG_DECLARE(ui_img_folder_transparent_resized_outlined_png);    // assets/folder_transparent_resized_outlined.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
